//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudweb_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHYSICALPERSON
    {
        public int ID { get; set; }
        public int PERSON_ID { get; set; }
        public decimal SALARY { get; set; }
        public System.DateTime DATEBIRTH { get; set; }
        public string GENRE { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
